name: production
on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed
    branches:
      - main
      - master

protection_rules:
  required_reviewers:
    - bert
  wait_timer:
    minutes: 0
  deployment_branches:
    protected_branches: true
    custom_branch_policies: false 